### ISSUE TITLE
[C001:Tjenesteeier] Tilby brukervennlig løsning for å sende og motta store filer

### ISSUE THREAD

**Issue by githagen** [githagen/altinn-test-repo#540]
Title: Tilby brukervennlig løsning for å sende og motta store filer
Issue type: epic
Concept no: C001
Stage: Onboarding

### Short description
TBD.

### Features
Altinn GUI for avsender:
- [x] Drag&drop filer for opplasting
- [ ] Framdriftsindikator for opplastiing
- [ ] Presentasjon av sanntids sporing i avsenders GUI

Altinn GUI for mottaker:
- [x] Drag&drop filer for nedlasting
- [ ] Framdriftsindikator for opplastiing
- [ ] Lesebekreftelse

### User Epic
User role: Tjenesteeier
User-epic: Tilrettelegge brukervennlige løsninger for å sende og motta store filer

Short description: 
TBD.

### Tasks (this issue)
- [x] #570
- [ ] En annen task?

### Related user stories
- [ ] User story 1  

### Blocking issues
- [ ] Blocking issue 1

### Dependent issues/tasks
- [ ] Dependent issue 1

### Additional Information
_Automatically updated properties - not to be edited manually:_
- _ArchiConceptID_: id-1be3848f7cc2471491332187ac6a14ad
- _GithubIssueID_: I_kwDOKG7zDs5u5o9w
